name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: maven

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Build with Maven
        run: mvn clean test -Dselenide.remote=http://localhost:4444/wd/hub
